// Audio
// ===========================
export const AUDIO_ENABLED = true;
export const AUDIO_ENABLED_PAPER_IDS = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "70",
  "71",
  "72",
  "73",
  "74",
  "75",
  "76",
  "77",
  "78",
  "79",
  "80",
  "81",
  "82",
  "83",
  "84",
  "85",
  "86",
  "87",
  "88",
  "89",
  "90",
  "91",
  "92",
  "93",
  "94",
  "95",
  "96",
  "97",
  "98",
  "99",
  "100",
  "101",
  "102",
  "103",
];
export const PAPER_ID_TO_MP3_URL = {
  "0": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "1": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "2": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "3": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "4": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "5": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "6": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "7": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "8": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "9": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "10": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "11": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "12": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "13": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "14": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "15": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "16": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "17": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "18": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "19": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "20": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "21": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "22": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "23": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "24": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "25": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "26": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "27": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "28": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "29": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "30": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "31": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "32": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "33": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "34": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "35": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "36": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "37": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "38": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "39": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "40": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "41": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "42": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "43": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "44": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "45": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "46": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "47": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "48": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "49": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "50": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "51": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "52": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "53": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "54": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "55": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "56": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "57": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "58": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "59": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "60": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "61": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "62": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "63": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "64": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "65": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "66": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "67": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "68": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "69": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "70": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "71": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "72": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "73": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "74": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "75": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "76": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "77": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "78": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "79": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "80": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "81": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "82": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "83": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "84": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "85": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "86": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "87": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "88": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "89": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "90": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "91": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "92": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "93": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "94": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "95": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "96": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "97": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "98": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "99": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "100": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "101": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "102": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "103": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
};
export const NEXT_AUDIO_DELAY = 300; // Milliseconds

// Reading
// ===========================
export const AVERAGE_READING_SPEED = 400; // Words per minute
