// Audio
// ===========================
export const AUDIO_ENABLED = true;
export const AUDIO_ENABLED_PAPER_IDS = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
];
export const PAPER_ID_TO_MP3_URL = {
  "0": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "1": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "2": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "3": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "4": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "5": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "6": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "7": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "8": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "9": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "10": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "11": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "12": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "13": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "14": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "15": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "16": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "17": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "18": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "19": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "20": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "21": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "22": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "23": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "24": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "25": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "26": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "27": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "28": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "29": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "30": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "31": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "32": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "33": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "34": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "35": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "36": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "37": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "38": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "39": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "40": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "41": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "42": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "43": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "44": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "45": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "46": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "47": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "48": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "49": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
  "50": `${process.env.NEXT_PUBLIC_AUDIO_FILES_CDN}/tts-1-hd-nova-`,
};
export const NEXT_AUDIO_DELAY = 300; // Milliseconds

// Reading
// ===========================
export const AVERAGE_READING_SPEED = 400; // Words per minute
