export const paperLabels = [
  "Administration",
  "Angelology",
  "Anthropology",
  "Arts",
  "Biology",
  "Christology",
  "Comparative Religion",
  "Cosmology",
  "Education",
  "Eschatology",
  "Ethics",
  "Governance",
  "History",
  "Law",
  "Mythology",
  "Philosophy",
  "Politics",
  "Psychology",
  "Religious Studies",
  "Science",
  "Sociology",
  "Spirituality",
  "Theology",
];

export const paperLabelsLookup = {
  "0": ["Philosophy", "Theology"],
  "1": ["Theology", "Philosophy"],
  "2": ["Theology", "Philosophy"],
  "3": ["Theology", "Philosophy"],
  "4": ["Theology", "Cosmology"],
  "5": ["Theology", "Philosophy"],
  "6": ["Theology", "Philosophy"],
  "7": ["Theology", "Cosmology"],
  "8": ["Theology", "Philosophy"],
  "9": ["Theology", "Cosmology"],
  "10": ["Theology", "Philosophy"],
  "11": ["Theology", "Cosmology"],
  "12": ["Cosmology", "Theology"],
  "13": ["Theology", "Cosmology"],
  "14": ["Theology", "Cosmology"],
  "15": ["Theology", "Cosmology"],
  "16": ["Theology", "Philosophy"],
  "17": ["Theology", "Cosmology"],
  "18": ["Theology", "Philosophy"],
  "19": ["Theology", "Philosophy"],
  "20": ["Theology", "Philosophy"],
  "21": ["Theology", "Philosophy"],
  "22": ["Theology", "Philosophy"],
  "23": ["Theology", "Cosmology"],
  "24": ["Theology", "Philosophy"],
  "25": ["Theology", "Cosmology"],
  "26": ["Theology", "Cosmology"],
  "27": ["Theology", "Philosophy"],
  "28": ["Theology", "Cosmology"],
  "29": ["Theology", "Science"],
  "30": ["Theology", "Philosophy"],
  "31": ["Theology", "Eschatology"],
  "32": ["Cosmology", "Science"],
  "33": ["Theology", "Administration"],
  "34": ["Theology", "Philosophy"],
  "35": ["Theology", "Philosophy"],
  "36": ["Biology", "Science"],
  "37": ["Theology", "Cosmology"],
  "38": ["Theology", "Cosmology"],
  "39": ["Theology", "Angelology"],
  "40": ["Theology", "Eschatology"],
  "41": ["Cosmology", "Science"],
  "42": ["Science", "Philosophy"],
  "43": ["Cosmology", "Theology"],
  "44": ["Theology", "Arts"],
  "45": ["Theology", "Administration"],
  "46": ["Theology", "Cosmology"],
  "47": ["Theology", "Eschatology"],
  "48": ["Theology", "Eschatology"],
  "49": ["Cosmology", "Theology"],
  "50": ["Theology", "Governance"],
  "51": ["Theology", "Anthropology"],
  "52": ["Theology", "History"],
  "53": ["Theology", "History"],
  "54": ["Theology", "Ethics"],
  "55": ["Theology", "Eschatology"],
  "56": ["Theology", "Philosophy"],
  "57": ["Cosmology", "Science"],
  "58": ["Biology", "Science"],
  "59": ["Biology", "History"],
  "60": ["Biology", "History"],
  "61": ["Biology", "History"],
  "62": ["Anthropology", "History"],
  "63": ["Anthropology", "History"],
  "64": ["Anthropology", "Sociology"],
  "65": ["Science", "Theology"],
  "66": ["Theology", "History"],
  "67": ["Theology", "History"],
  "68": ["Sociology", "History"],
  "69": ["Sociology", "Anthropology"],
  "70": ["Politics", "Sociology"],
  "71": ["Politics", "Sociology"],
  "72": ["Politics", "Sociology"],
  "73": ["Theology", "History"],
  "74": ["Theology", "Anthropology"],
  "75": ["Theology", "Ethics"],
  "76": ["Theology", "History"],
  "77": ["Theology", "Mythology"],
  "78": ["Anthropology", "Sociology"],
  "79": ["History", "Anthropology"],
  "80": ["History", "Anthropology"],
  "81": ["Sociology", "History"],
  "82": ["Sociology", "Anthropology"],
  "83": ["Sociology", "Anthropology"],
  "84": ["Sociology", "Anthropology"],
  "85": ["Theology", "Anthropology"],
  "86": ["Theology", "Sociology"],
  "87": ["Theology", "Anthropology"],
  "88": ["Anthropology", "Theology"],
  "89": ["Theology", "Ethics"],
  "90": ["Anthropology", "Theology"],
  "91": ["Theology", "Sociology"],
  "92": ["Theology", "Sociology"],
  "93": ["Theology", "History"],
  "94": ["Theology", "History"],
  "95": ["Theology", "History"],
  "96": ["Theology", "History"],
  "97": ["Theology", "History"],
  "98": ["Theology", "History"],
  "99": ["Theology", "Sociology"],
  "100": ["Theology", "Psychology"],
  "101": ["Theology", "Philosophy"],
  "102": ["Theology", "Philosophy"],
  "103": ["Theology", "Psychology"],
  "104": ["Theology", "Philosophy"],
  "105": ["Theology", "Philosophy"],
  "106": ["Theology", "Cosmology"],
  "107": ["Theology", "Philosophy"],
  "108": ["Theology", "Philosophy"],
  "109": ["Theology", "Cosmology"],
  "110": ["Theology", "Philosophy"],
  "111": ["Theology", "Philosophy"],
  "112": ["Theology", "Eschatology"],
  "113": ["Theology", "Angelology"],
  "114": ["Theology", "Governance"],
  "115": ["Theology", "Philosophy"],
  "116": ["Theology", "Philosophy"],
  "117": ["Theology", "Philosophy"],
  "118": ["Theology", "Cosmology"],
  "119": ["Theology", "Christology"],
  "120": ["Theology", "Christology"],
  "121": ["History", "Theology"],
  "122": ["History", "Theology"],
  "123": ["History", "Theology"],
  "124": ["History", "Theology"],
  "125": ["History", "Theology"],
  "126": ["History", "Theology"],
  "127": ["History", "Theology"],
  "128": ["History", "Theology"],
  "129": ["History", "Theology"],
  "130": ["History", "Theology"],
  "131": ["History", "Comparative Religion", "Theology"],
  "132": ["History", "Theology"],
  "133": ["History", "Theology"],
  "134": ["History", "Theology"],
  "135": ["History", "Theology"],
  "136": ["History", "Spirituality", "Theology"],
  "137": ["History", "Theology"],
  "138": ["History", "Education", "Theology"],
  "139": ["History", "Religious Studies"],
  "140": ["History", "Religious Studies"],
  "141": ["History", "Theology"],
  "142": ["History", "Religious Studies"],
  "143": ["History", "Sociology"],
  "144": ["History", "Sociology"],
  "145": ["History", "Theology"],
  "146": ["History", "Religious Studies"],
  "147": ["History", "Theology"],
  "148": ["History", "Education", "Theology"],
  "149": ["History", "Religious Studies"],
  "150": ["History", "Religious Studies"],
  "151": ["History", "Education", "Theology"],
  "152": ["History", "Sociology"],
  "153": ["History", "Sociology"],
  "154": ["History", "Theology"],
  "155": ["History", "Sociology"],
  "156": ["History", "Theology"],
  "157": ["History", "Theology"],
  "158": ["History", "Theology"],
  "159": ["History", "Sociology"],
  "160": ["History", "Philosophy", "History"],
  "161": ["History", "Philosophy", "History"],
  "162": ["History", "Religious Studies"],
  "163": ["History", "Religious Studies"],
  "164": ["History", "Religious Studies"],
  "165": ["History", "Religious Studies"],
  "166": ["History", "Theology"],
  "167": ["History", "Sociology"],
  "168": ["History", "Theology"],
  "169": ["History", "Education", "Theology"],
  "170": ["History", "Theology", "Philosophy"],
  "171": ["History", "Theology"],
  "172": ["History", "Theology"],
  "173": ["History", "Religious Studies"],
  "174": ["History", "Theology"],
  "175": ["History", "Education", "Theology"],
  "176": ["History", "Theology"],
  "177": ["History", "Sociology"],
  "178": ["History", "Sociology"],
  "179": ["History", "Theology"],
  "180": ["History", "Education", "Theology"],
  "181": ["History", "Ethics", "Theology"],
  "182": ["History", "Theology"],
  "183": ["History", "Theology"],
  "184": ["History", "Law"],
  "185": ["History", "Law"],
  "186": ["History", "Theology"],
  "187": ["History", "Theology"],
  "188": ["History", "Theology"],
  "189": ["History", "Theology"],
  "190": ["History", "Theology"],
  "191": ["History", "Theology"],
  "192": ["History", "Theology"],
  "193": ["History", "Theology"],
  "194": ["History", "Theology", "Philosophy"],
  "195": ["History", "Theology"],
  "196": ["Theology", "Philosophy"],
};
