export const paperLabels = [
  "Angelology",
  "Anthropology",
  "Art",
  "Astronomy",
  "Biology",
  "Christology",
  "Cosmic Administration",
  "Cosmology",
  "Eschatology",
  "Ethics",
  "Evolution",
  "History",
  "Paleontology",
  "Philosophy",
  "Political Science",
  "Science",
  "Sociology",
  "Spirituality",
  "Theology",
  "Utopian Studies",
];
