export const paperLabels = [
  "Angelology",
  "Anthropology",
  "Art",
  "Astronomy",
  "Biology",
  "Christology",
  "Cosmic Administration",
  "Cosmology",
  "After Life",
  "Ethics",
  "History",
  "Paleontology",
  "Philosophy",
  "Political Science",
  "Science",
  "Sociology",
  "Spirituality",
  "Theology",
  "Utopian Studies",
];

export const paperLabelsLookup = {
  "0": ["Theology", "Cosmology", "Philosophy", "Spirituality"],
  "1": ["Spirituality", "Theology", "Philosophy"],
  "2": ["Spirituality", "Theology", "Philosophy"],
  "3": ["Spirituality", "Theology", "Philosophy"],
  "4": ["Cosmology", "Theology", "Philosophy"],
  "5": ["Spirituality", "Philosophy"],
  "6": ["Spirituality", "Theology", "Philosophy"],
  "7": ["Cosmology", "Theology", "Philosophy"],
  "8": ["Spirituality", "Theology", "Philosophy"],
  "9": ["Cosmology", "Theology", "Philosophy"],
  "10": ["Spirituality", "Theology", "Philosophy"],
  "11": ["Spirituality", "Cosmology", "Philosophy"],
  "12": ["Cosmology", "Science", "Philosophy"],
  "13": ["Spirituality", "Theology", "Cosmic Administration"],
  "14": ["Cosmology", "Theology", "Spirituality"],
  "15": ["Cosmology", "Theology", "Science"],
  "16": ["Spirituality", "Theology", "Cosmic Administration"],
  "17": ["Spirituality", "Theology", "Cosmic Administration"],
  "18": ["Theology", "Cosmic Administration", "Philosophy"],
  "19": ["Theology", "After Life", "Philosophy"],
  "20": ["Theology", "Christology", "After Life"],
  "21": ["Theology", "Cosmic Administration"],
  "22": ["Theology", "Cosmic Administration"],
  "23": ["Cosmology", "Cosmic Administration"],
  "24": ["Theology", "Cosmic Administration"],
  "25": ["Spirituality", "Cosmic Administration"],
  "26": ["Theology", "Spirituality"],
  "27": ["Theology", "Angelology", "Ethics"],
  "28": ["Theology", "Angelology", "Cosmic Administration"],
  "29": ["Cosmology", "Science"],
  "30": ["Theology", "Cosmic Administration"],
  "31": ["After Life", "Theology"],
  "32": ["Cosmology", "Theology", "Astronomy", "Science"],
  "33": ["Theology", "Cosmic Administration"],
  "34": ["Theology", "Cosmic Administration", "Spirituality"],
  "35": ["Theology", "Cosmic Administration", "Spirituality"],
  "36": ["Science", "Theology"],
  "37": ["Spirituality", "Theology", "Cosmic Administration"],
  "38": ["Angelology", "Spirituality", "Theology", "After Life"],
  "39": ["Angelology", "Cosmic Administration", "Theology"],
  "40": ["Spirituality", "Theology"],
  "41": ["Science", "Cosmology"],
  "42": ["Science", "Philosophy", "Cosmology"],
  "43": ["Astronomy", "Cosmic Administration", "Theology"],
  "44": ["Theology", "Art"],
  "45": ["Cosmic Administration", "Theology", "Spirituality"],
  "46": ["Astronomy", "Theology", "Cosmic Administration"],
  "47": ["After Life", "Spirituality"],
  "48": ["Philosophy", "Spirituality", "After Life"],
  "49": ["Science", "Astronomy", "Theology", "Biology"],
  "50": ["Theology", "Cosmic Administration"],
  "51": ["Theology", "Anthropology", "Cosmic Administration"],
  "52": ["History", "Science", "Anthropology"],
  "53": ["Theology", "Ethics", "Philosophy"],
  "54": ["Theology", "Ethics", "Philosophy"],
  "55": ["After Life", "Utopian Studies", "Theology"],
  "56": ["Philosophy", "Theology", "Cosmology"],
  "57": ["Science", "Cosmology", "History"],
  "58": ["Biology", "Science", "History"],
  "59": ["Paleontology", "Biology", "History", "Science"],
  "60": ["Paleontology", "Biology", "History", "Science"],
  "61": ["Paleontology", "Biology", "Science", "History"],
  "62": ["Anthropology", "Science", "History"],
  "63": ["Anthropology", "Sociology", "Science", "History"],
  "64": ["Anthropology", "Sociology", "Science", "History"],
  "65": ["Theology", "Science", "Philosophy", "History"],
  "66": ["Theology", "Cosmic Administration", "History"],
  "67": ["Theology", "Ethics", "History"],
  "68": ["Sociology", "History"],
  "69": ["Sociology", "Anthropology", "History"],
  "70": ["Political Science", "History", "Sociology"],
  "71": ["Political Science", "Sociology"],
  "72": ["Political Science", "Utopian Studies", "Sociology"],
  "73": ["Theology", "Anthropology", "History"],
  "74": ["Theology", "Anthropology", "History"],
  "75": ["Theology", "Ethics", "History", "Anthropology"],
  "76": ["Theology", "Anthropology", "History"],
  "77": ["Theology", "Spirituality"],
  "78": ["Anthropology", "History", "Sociology"],
  "79": ["Anthropology", "History", "Sociology"],
  "80": ["Anthropology", "History", "Sociology"],
  "81": ["Sociology", "History"],
  "82": ["Sociology", "Anthropology", "History"],
  "83": ["Sociology", "Anthropology"],
  "84": ["Sociology", "Anthropology"],
  "85": ["Theology", "Spirituality"],
  "86": ["Theology", "Spirituality"],
  "87": ["Theology", "Spirituality"],
  "88": ["Sociology", "Anthropology"],
  "89": ["Theology", "Ethics"],
  "90": ["Sociology", "Anthropology"],
  "91": ["Spirituality", "Theology"],
  "92": ["Theology", "Sociology"],
  "93": ["Theology", "Philosophy"],
  "94": ["Theology", "Philosophy", "History"],
  "95": ["Theology", "Philosophy", "History"],
  "96": ["Theology", "Philosophy"],
  "97": ["Theology", "Philosophy"],
  "98": ["Theology", "Philosophy", "History"],
  "99": ["Sociology", "Theology", "Ethics"],
  "100": ["Spirituality", "Philosophy"],
  "101": ["Theology", "Philosophy", "Spirituality"],
  "102": ["Theology", "Philosophy", "Spirituality"],
  "103": ["Theology", "Philosophy", "Spirituality"],
  "104": ["Theology", "Philosophy"],
  "105": ["Theology", "Philosophy"],
  "106": ["Cosmology", "Philosophy", "Theology"],
  "107": ["Theology", "Spirituality", "Philosophy"],
  "108": ["Theology", "Philosophy"],
  "109": ["Theology", "Philosophy"],
  "110": ["Theology", "Spirituality"],
  "111": ["Theology", "Spirituality"],
  "112": ["Theology", "After Life", "Philosophy"],
  "113": ["Angelology", "Theology"],
  "114": ["Cosmic Administration", "Theology", "Philosophy"],
  "115": ["Theology", "Cosmology", "Philosophy"],
  "116": ["Theology", "Cosmology", "Philosophy"],
  "117": ["Theology", "Spirituality", "Philosophy"],
  "118": ["Cosmology", "Theology", "Philosophy", "Science"],
  "119": ["Theology", "Christology", "Spirituality"],
  "120": ["Theology", "Christology", "History"],
  "121": ["Theology", "Christology", "History"],
  "122": ["Theology", "Christology", "History"],
  "123": ["Theology", "Christology", "History"],
  "124": ["Theology", "Christology", "History"],
  "125": ["Theology", "Christology", "History"],
  "126": ["Theology", "Christology", "History"],
  "127": ["Theology", "Christology", "History"],
  "128": ["Theology", "Christology", "History"],
  "129": ["Theology", "Christology", "History"],
  "130": ["Theology", "Christology", "History"],
  "131": ["Theology", "Christology", "History", "Philosophy"],
  "132": ["Theology", "Christology", "History", "Philosophy"],
  "133": ["Theology", "Christology", "History", "Philosophy"],
  "134": ["Theology", "Christology", "History", "Philosophy"],
  "135": ["Theology", "Christology", "History", "Philosophy"],
  "136": ["Theology", "Christology", "History", "Philosophy"],
  "137": ["Theology", "Christology", "History", "Philosophy"],
  "138": ["Theology", "Christology", "History", "Philosophy"],
  "139": ["Theology", "Christology", "History", "Philosophy"],
  "140": ["Theology", "Christology", "History", "Philosophy"],
  "141": ["Theology", "Christology", "History", "Philosophy"],
  "142": ["Theology", "Christology", "History", "Philosophy"],
  "143": ["Theology", "Christology", "History", "Philosophy"],
  "144": ["Theology", "Christology", "History", "Philosophy"],
  "145": ["Theology", "Christology", "History", "Philosophy"],
  "146": ["Theology", "Christology", "History", "Philosophy"],
  "147": ["Theology", "Christology", "History", "Philosophy"],
  "148": ["Theology", "Christology", "History", "Philosophy"],
  "149": ["Theology", "Christology", "History", "Philosophy"],
  "150": ["Theology", "Christology", "History", "Philosophy"],
  "151": ["Theology", "Christology", "History", "Philosophy"],
  "152": ["Theology", "Christology", "History", "Philosophy"],
  "153": ["Theology", "Christology", "History", "Philosophy"],
  "154": ["Theology", "Christology", "History", "Philosophy"],
  "155": ["Theology", "Christology", "History", "Philosophy"],
  "156": ["Theology", "Christology", "History", "Philosophy"],
  "157": ["Theology", "Christology", "History", "Philosophy"],
  "158": ["Theology", "Christology", "History", "Philosophy"],
  "159": ["Theology", "Christology", "History", "Philosophy"],
  "160": ["Theology", "Christology", "History", "Philosophy"],
  "161": ["Theology", "Christology", "History", "Philosophy"],
  "162": ["Theology", "Christology", "History", "Philosophy"],
  "163": ["Theology", "Christology", "History", "Philosophy"],
  "164": ["Theology", "Christology", "History", "Philosophy"],
  "165": ["Theology", "Christology", "History", "Philosophy"],
  "166": ["Theology", "Christology", "History", "Philosophy"],
  "167": ["Theology", "Christology", "History", "Philosophy"],
  "168": ["Theology", "Christology", "History", "Philosophy"],
  "169": ["Theology", "Christology", "History", "Philosophy"],
  "170": ["Theology", "Christology", "History", "Philosophy"],
  "171": ["Theology", "Christology", "History", "Philosophy"],
  "172": ["Theology", "Christology", "History", "Philosophy"],
  "173": ["Theology", "Christology", "History", "Philosophy"],
  "174": ["Theology", "Christology", "History", "Philosophy"],
  "175": ["Theology", "Christology", "History", "Philosophy"],
  "176": ["Theology", "Christology", "History", "Philosophy"],
  "177": ["Theology", "Christology", "History", "Philosophy"],
  "178": ["Theology", "Christology", "History", "Philosophy"],
  "179": ["Theology", "Christology", "History", "Philosophy"],
  "180": ["Theology", "Christology", "History", "Philosophy"],
  "181": ["Theology", "Christology", "History", "Philosophy"],
  "182": ["Theology", "Christology", "History", "Philosophy"],
  "183": ["Theology", "Christology", "History", "Philosophy"],
  "184": ["Theology", "Christology", "History", "Philosophy"],
  "185": ["Theology", "Christology", "History", "Philosophy"],
  "186": ["Theology", "Christology", "History", "Philosophy"],
  "187": ["Theology", "Christology", "History", "Philosophy"],
  "188": ["Theology", "Christology", "History", "Philosophy"],
  "189": ["Theology", "Christology", "History", "Philosophy"],
  "190": ["Theology", "Christology", "History", "Philosophy"],
  "191": ["Theology", "Christology", "History", "Philosophy"],
  "192": ["Theology", "Christology", "History", "Philosophy"],
  "193": ["Theology", "Christology", "History", "Philosophy"],
  "194": ["Theology", "Christology", "History", "Philosophy"],
  "195": ["Theology", "Christology", "History", "Philosophy"],
  "196": ["Theology", "Christology", "History", "Philosophy"],
};
